backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Posts" # Used in the UI
    folder: "writing/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "layout.liquid" }
      - { label: "Title", name: "pageTitle", widget: "string" }
media_folder: "img" # The path to the folder where the media files are stored
