module.exports = [
    {
        id: 1,
        title: "Commerce Website Redesign",
        year: "2023",
        type: "UI/UX Design and Development",
        subtitle: "A complete redesign of a commercial restaurant platform to improve user experience and conversion rates.",
        liveSite: "https://rasoi.parth.ninja",
        desktopImage: "/img/rasoi_desktop.png",
        mobileImage: "/img/rasoi_mobile.png",
        requirements: "Create a modern, responsive restaurant menu that clearly showcases dishes and pricing. Make it easy for users to browse, order, and pay online.",
        research: "Conducted user interviews, analyzed site analytics, and benchmarked against competitors. Identified key pain points and opportunities for improvement.",
        designProcess: "Created wireframes, prototypes, and high-fidelity mockups using Figma.",
        challenges: "Balancing a modern design with the existing brand identity, ensuring compatibility with legacy systems.",
        outcome: "Increased conversion rates by 25%, reduced bounce rates on mobile by 15%. Positive feedback from users and stakeholders.",
    },
    {
        id: 2,
        title: "Personal Blog Site",
        year: "2022",
        type: "UI/UX Design and Development",
        subtitle: "Designed and developed a personal blog site to showcase my brand and writing samples.",
        liveSite: "https://parth.ninja",
        desktopImage: "/img/personal_desktop.png",
        mobileImage: "/img/personal_mobile.png",
        requirements: "Create a clean, modern site that reflects my personal brand and showcases my writing and design. Add motifs that reflect my personality and interests.",
        research: "Reviewed popular personal blogs, analyzed design trends, and gathered feedback from peers. Developed a content strategy to highlight my best work.",
        designProcess: "Developed the site using HTML, CSS, and NodeJS with a focus on SEO and responsiveness.",
        challenges: "Ensuring fast load times without compromising on visual appeal, meeting accessibility standards.",
        outcome: "Site featured in design showcases and webrings, received positive feedback from industry professionals.",
    },
    {
        id: 3,
        title: "Project Portfolio",
        year: "2024",
        type: "Product Design, Branding, and Development",
        subtitle: "Designed and developed a project portfolio to showcase my work and skills to potential clients and employers.",
        liveSite: "https://work.parth.ninja",
        desktopImage: "/img/platinum_desktop.png",
        mobileImage: "/img/platinum_mobile.png",
        requirements: "Create a visually appealing portfolio that highlights my design process, skills, and projects. Develop a personal brand that reflects my design philosophy.",
        research: "Analyzed popular design portfolios, identified key elements and trends. Developed a brand strategy and visual identity. A/B tested design elements for optimal engagement.",
        designProcess: "Designed the site in Figma, developed it using HTML, CSS, and NodeJS. Integrated animations and interactions to enhance user experience. Conducted usability testing to refine the design.",
        challenges: "Balancing creativity with professionalism, ensuring the site reflects my personality while appealing to a wide audience.",
        outcome: "Over 1000 unique visitors in the first month, positive feedback from industry professionals and potential clients.",
    }
];
