// src/_data/projects.js
module.exports = [
    {
        id: 1,
        title: "Project One",
        subtitle: "An amazing project",
        image: "/img/projects/2019site.webp",
        tech: ["HTML", "CSS", "JavaScript"],
        link: "/projects/project-one",
        liveSite: "https://example.com/project-one",
        year: 2020,
        description: "This is a description of the project. Hipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "Sans-serif",
        colors: ["#FF5733", "#33FF57", "#5733FF", "#c0c0c0", "#d3d3d3"],
        designDetails: "Clean and minimalistic design",
        awards: ["Best Design Award", "Top Rated Project"]
    },
    {
        id: 2,
        title: "Project Two",
        subtitle: "Another remarkable project",
        image: "/img/projects/2020site.webp",
        tech: ["Node.js", "Express", "MongoDB"],
        link: "/projects/project-two",
        liveSite: "https://example.com/project-two",
        year: 2021,
        description: "This is a description of the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "Serif",
        colors: ["#3366FF", "#FF3366", "#66FF33", "#FF6633", "#33FF66"],
        designDetails: "Bold and vibrant design",
        awards: []
    },
    {
        id: 3,
        title: "Project Three",
        subtitle: "A third project",
        image: "/img/projects/2021site.webp",
        tech: ["React", "Redux", "Firebase"],
        link: "/projects/project-three",
        liveSite: "https://example.com/project-three",
        year: 2022,
        description: "This is a description of the project. Consec tetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "Monospace",
        colors: ["#FF9933", "#33FF99", "#9933FF", "#FF33FF", "#99FF33"],
        designDetails: "Modern and sleek design",
        awards: ["Best User Experience"]
    },
    {
        id: 4,
        title: "Project Four",
        subtitle: "A fourth project",
        image: "/img/projects/2022site.webp",
        tech: ["Vue", "Vuex", "MongoDB"],
        link: "/projects/project-four",
        liveSite: "https://example.com/project-four",
        year: 2023,
        description: "This is a description of the project. Dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "Cursive",
        colors: ["#FF3366", "#33FF33", "#3366FF"],
        designDetails: "Elegant and sophisticated design",
        awards: ["Innovation Award"]
    },
    {
        id: 5,
        title: "Project Five",
        subtitle: "A fifth project",
        image: "https://placehold.co/500x400/000000/FFF",
        tech: ["Angular", "NgRx", "Firebase"],
        link: "/projects/project-five",
        liveSite: "https://example.com/project-five",
        year: 2024,
        description: "This is a description of the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "Sans-serif",
        colors: ["#33FF99", "#9933FF", "#FF9933"],
        designDetails: "Dynamic and interactive design",
        awards: []
    },
    {
        id: 6,
        title: "Project Six",
        subtitle: "A sixth project",
        image: "https://placehold.co/500x400/000000/FFF",
        tech: ["Python", "Django", "PostgreSQL"],
        link: "/projects/project-six",
        liveSite: "https://example.com/project-six",
        year: 2025,
        description: "This is a description of the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "Serif",
        colors: ["#FF6600", "#0066FF", "#66FF00"],
        designDetails: "Sleek and professional design",
        awards: ["Outstanding Performance"]
    },
    {
        id: 7,
        title: "Project Seven",
        subtitle: "A seventh project",
        image: "https://placehold.co/500x400/000000/FFF",
        tech: ["Ruby on Rails", "MySQL", "Bootstrap"],
        link: "/projects/project-seven",
        liveSite: "https://example.com/project-seven",
        year: 2026,
        description: "This is a description of the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "Monospace",
        colors: ["#FFCC00", "#00CCFF", "#CCFF00"],
        designDetails: "Minimalistic and clean design",
        awards: []
    },
    {
        id: 8,
        title: "Project Eight",
        subtitle: "An eighth project",
        image: "https://placehold.co/500x400/000000/FFF",
        tech: ["PHP", "Laravel", "MySQL"],
        link: "/projects/project-eight",
        liveSite: "https://example.com/project-eight",
        year: 2027,
        description: "This is a description of the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "Cursive",
        colors: ["#CC0000", "#00CC00", "#0000CC"],
        designDetails: "Creative and unique design",
        awards: ["Most Innovative Project"]
    },
    {
        id: 9,
        title: "Project Nine",
        subtitle: "A ninth project",
        image: "https://placehold.co/500x400/000000/FFF",
        tech: ["Flutter", "Dart", "Firebase"],
        link: "/projects/project-nine",
        liveSite: "https://example.com/project-nine",
        year: 2028,
        description: "This is a description of the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "Sans-serif",
        colors: ["#9900CC", "#00CC99", "#CC9900"],
        designDetails: "User-friendly and intuitive design",
        awards: ["Best Mobile App"]
    }
];

