// src/_data/projects.js
module.exports = [
    {
        id: 1,
        title: "Cana",
        subtitle: "A 3D Printer for Drinks",
        image: "/img/projects/2019site.webp",
        tech: ["TWIG", "Shopify", "Wordpress"],
        link: "/projects/project-one",
        liveSite: "https://cana.com",
        year: 2020,
        description: "A 3D printer for drinks.",
        typography: "Degular + Roboto Mono",
        colors: ["#003e4e", "#fff", "#6dcada", "#f20044", "#d3e900"],
        designDetails: "Clean and minimalistic design",
        awards: ["Patrick Stewart Approves of it"]
    },
    {
        id: 2,
        title: "The Life Story",
        subtitle: "Another remarkable project",
        image: "/img/projects/2020site.webp",
        tech: ["Vue.js", "Webpack", "Ajax"],
        link: "/projects/project-two",
        liveSite: "https://thelifestory.org",
        year: 2021,
        description: "This is a description of the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "FreightSans + FreightSans Pro",
        colors: ["#FFFFFF", "#2E437D", "#E3E8EE", "#FF685B", "#D4DEED"],
        designDetails: "Bold and vibrant design"
    },
    {
        id: 3,
        title: "UHG",
        subtitle: "A third project",
        image: "/img/projects/2021site.webp",
        tech: ["Nunjucks", "Gulp", "DDEV"],
        link: "/projects/project-three",
        liveSite: "https://uhg.com",
        year: 2022,
        description: "This is a description of the project. Consec tetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "Optum Sans + Graphik",
        colors: ["#002677", "#0066F5", "#CCE0FC", "#FFFFFF", "#DA5AB6"],
        designDetails: "Modern and sleek design"
    },
    {
        id: 4,
        title: "Choose Kindness",
        subtitle: "A fourth project",
        image: "/img/projects/2022site.webp",
        tech: ["Wordpress", "SCSS", "COMPOSER"],
        link: "/projects/project-four",
        liveSite: "https://example.com/project-four",
        year: 2023,
        description: "This is a description of the project. Dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "Tenon + Work Sans",
        colors: ["#ffc300", "#007B5A", "#fbf4f2", "#2e50fF", "#ff376b"],
        designDetails: "Elegant and sophisticated design",
        awards: ["Webby Award"]
    },
    {
        id: 5,
        title: "Nike SB",
        subtitle: "A fifth project",
        image: "https://placehold.co/500x400/000000/FFF",
        tech: ["React", "DDEV", "SASS", "Chokidar"],
        link: "/projects/project-five",
        liveSite: "https://example.com/project-five",
        year: 2024,
        description: "This is a description of the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "Bookmania + Roboto Mono + Gothic FB Wide",
        colors: ["#ff6123", "#79c06b", "#70c8fe", "#000000", "#f4e372"],
        designDetails: "Dynamic and interactive design"
    },
    {
        id: 6,
        title: "Rally Health",
        subtitle: "A sixth project",
        image: "https://placehold.co/500x400/000000/FFF",
        tech: ["Craft", "Docker", "Jenkins"],
        link: "/projects/project-six",
        liveSite: "https://example.com/project-six",
        year: 2025,
        description: "This is a description of the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "Helvetica Nue + Adelle",
        colors: ["#F26C32", "#48BFB0", "#F5885C", "#239F8E", "#4d4d4d"],
        designDetails: "Sleek and professional design"
    },
    {
        id: 7,
        title: "malarkey roofing",
        subtitle: "A seventh project",
        image: "https://placehold.co/500x400/000000/FFF",
        tech: ["composer", "webpack", "babel"],
        link: "/projects/project-seven",
        liveSite: "https://example.com/project-seven",
        year: 2026,
        description: "This is a description of the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "Geogrotesque",
        colors: ["#F8F8F8", "#D28122", "#24C26C", "#000", "#efefef"],
        designDetails: "Minimalistic and clean design"
    },
    {
        id: 8,
        title: "Adobe Procurement",
        subtitle: "An eighth project",
        image: "https://placehold.co/500x400/000000/FFF",
        tech: ["vue", "spectrumCSS", "babel"],
        link: "/projects/project-eight",
        liveSite: "https://example.com/project-eight",
        year: 2027,
        description: "This is a description of the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "Cursive",
        colors: ["#0265DC", "#e3342f", "#fbc447", "#4dc0b5", "#9561e2"],
        designDetails: "Creative and unique design"
    },
    {
        id: 9,
        title: "UHG Sustainability",
        subtitle: "A ninth project",
        image: "https://placehold.co/500x400/000000/FFF",
        tech: ["php", "grunt", "DDEV"],
        link: "/projects/project-nine",
        liveSite: "https://example.com/project-nine",
        year: 2028,
        description: "This is a description of the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "Optum Sans + Graphik",
        colors: ["#002677", "#0066F5", "#CCE0FC", "#FFFFFF", "#DA5AB6"],
        designDetails: "User-friendly and intuitive design"
    },
    {
        id: 10,
        title: "Disney CSR",
        subtitle: "A ninth project",
        image: "https://placehold.co/500x400/000000/FFF",
        tech: ["wordpress", "lottie", "docker"],
        link: "/projects/project-ten",
        liveSite: "https://example.com/project-nine",
        year: 2028,
        description: "This is a description of the project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "Museo Sans + Inspire TWDC",
        colors: ["#fff5f4", "#081351", "#ff6621", "#00d99e", "#e2b2ff"],
        designDetails: "User-friendly and intuitive design"
    },
    {
        id: 11,
        title: "Listening Sessions",
        subtitle: "A ninth project",
        image: "https://placehold.co/500x400/000000/FFF",
        tech: ["react", "gatsby", "scss"],
        link: "/projects/project-eleven",
        liveSite: "https://example.com/project-nine",
        year: 2028,
        description: "This is a description of the project. Consec tetur adipiscing elit. Nullam nec purus nec nunc ultricies aliquam. Nullam nec purus nec nunc ultricies aliquam.",
        typography: "FreightSans + FreightSans Pro",
        colors: ["#1c1c1c", "#41d2af", "#205f86", "#206f53", "#5c80ee"],
    }
];

